baseURL: http://example.com/
languageCode: en-us
title: Ticky Tacky Dark
theme: ticky_tacky_dark
disableKinds:
  - taxonomy
  - taxonomyTerm
enableEmoji: yes
params:
  description: The demonstration page for the Hugo Ticky Tacky Dark theme.
  favicon: favicon.ico
  headername: tickytackydark
  images:
    - img/header01.jpg
    - img/header02.jpg
Author:
  email: kc0bfv@gmail.com
  name: Karl Sickendick
